version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - '15432:5432'
    env_file:
      - .env
    volumes:
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      # - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    healthcheck:
      test: [CMD-SHELL, pg_isready -U $POSTGRES_USER -d $POSTGRES_DB]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis

    ports:
      - '6560:6379'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  nest-postgres:
    name: nest-postgres-db
