#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$POSTGRES_USER" WITH ENCRYPTED PASSWORD "$POSTGRES_PASSWORD";
	CREATE DATABASE "$POSTGRES_DB";
	GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
EOSQL
